services:
  mugdoc-docs-site-docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mugdoc-docs-site-docs
    restart: unless-stopped
    networks:
      - caddy_net
    labels:
      caddy: mugdoc-docs-site.reposito.rio.br
      caddy.reverse_proxy: "{{upstreams 3013}}"
      caddy.encode: "gzip"
    expose:
      - 3013

networks:
  caddy_net:
    external: true
